//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWebServices.myReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myReference.myWebServiceasmxSoap")]
    public interface myWebServiceasmxSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployeesWithSalaryGreatherThan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getEmployeesWithSalaryGreatherThan(decimal salary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmployeesWithSalaryGreatherThan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getEmployeesWithSalaryGreatherThanAsync(decimal salary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface myWebServiceasmxSoapChannel : ConsumingWebServices.myReference.myWebServiceasmxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class myWebServiceasmxSoapClient : System.ServiceModel.ClientBase<ConsumingWebServices.myReference.myWebServiceasmxSoap>, ConsumingWebServices.myReference.myWebServiceasmxSoap {
        
        public myWebServiceasmxSoapClient() {
        }
        
        public myWebServiceasmxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public myWebServiceasmxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebServiceasmxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebServiceasmxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getEmployeesWithSalaryGreatherThan(decimal salary) {
            return base.Channel.getEmployeesWithSalaryGreatherThan(salary);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getEmployeesWithSalaryGreatherThanAsync(decimal salary) {
            return base.Channel.getEmployeesWithSalaryGreatherThanAsync(salary);
        }
    }
}
