//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingWebServices.WfcProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://schemas.datacontract.org/2004/07/WebServicesAndWCF")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkerAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WorkerSalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkerAge {
            get {
                return this.WorkerAgeField;
            }
            set {
                if ((this.WorkerAgeField.Equals(value) != true)) {
                    this.WorkerAgeField = value;
                    this.RaisePropertyChanged("WorkerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerId {
            get {
                return this.WorkerIdField;
            }
            set {
                if ((this.WorkerIdField.Equals(value) != true)) {
                    this.WorkerIdField = value;
                    this.RaisePropertyChanged("WorkerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerName {
            get {
                return this.WorkerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerNameField, value) != true)) {
                    this.WorkerNameField = value;
                    this.RaisePropertyChanged("WorkerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WorkerSalary {
            get {
                return this.WorkerSalaryField;
            }
            set {
                if ((this.WorkerSalaryField.Equals(value) != true)) {
                    this.WorkerSalaryField = value;
                    this.RaisePropertyChanged("WorkerSalary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WfcProxy.IWFCService")]
    public interface IWFCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/DoWork", ReplyAction="http://tempuri.org/IWFCService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/DoWork", ReplyAction="http://tempuri.org/IWFCService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/GetEmployeesById", ReplyAction="http://tempuri.org/IWFCService/GetEmployeesByIdResponse")]
        ConsumingWebServices.WfcProxy.Worker GetEmployeesById(int WorkerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/GetEmployeesById", ReplyAction="http://tempuri.org/IWFCService/GetEmployeesByIdResponse")]
        System.Threading.Tasks.Task<ConsumingWebServices.WfcProxy.Worker> GetEmployeesByIdAsync(int WorkerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/GetEmployees", ReplyAction="http://tempuri.org/IWFCService/GetEmployeesResponse")]
        ConsumingWebServices.WfcProxy.Worker[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFCService/GetEmployees", ReplyAction="http://tempuri.org/IWFCService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<ConsumingWebServices.WfcProxy.Worker[]> GetEmployeesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWFCServiceChannel : ConsumingWebServices.WfcProxy.IWFCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFCServiceClient : System.ServiceModel.ClientBase<ConsumingWebServices.WfcProxy.IWFCService>, ConsumingWebServices.WfcProxy.IWFCService {
        
        public WFCServiceClient() {
        }
        
        public WFCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public ConsumingWebServices.WfcProxy.Worker GetEmployeesById(int WorkerId) {
            return base.Channel.GetEmployeesById(WorkerId);
        }
        
        public System.Threading.Tasks.Task<ConsumingWebServices.WfcProxy.Worker> GetEmployeesByIdAsync(int WorkerId) {
            return base.Channel.GetEmployeesByIdAsync(WorkerId);
        }
        
        public ConsumingWebServices.WfcProxy.Worker[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<ConsumingWebServices.WfcProxy.Worker[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
    }
}
